- name: install nginx
  hosts: web
  become: yes
  tasks: 
    - name: intalling anginx package
      ansible.builtin.package:
        name: nginx
        state: present 
    - name: starting nginx
      ansible.builtin.service:
        name: nginx
        state: started
