- name: conditions
  hosts: localhost
  become: yes
  tasks: 
    - name: to check rebouser
      ansible.builtin.command: id roboshop
      register: user
      ignore_errors: true

    - name: print variable user
      ansible.builtin.debug:
        msg: "user is:{{user}}"

    - name: print variable user
      ansible.builtin.debug:
        msg: "user is:{{user.rc}}"

    - name: print variable user
      ansible.builtin.user:
        name: roboshop
    when: user.rc != 0

