- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: list of packages
    ansible.builtin.package:
     name: "{{item.name}}"
     state: "{{item.state}}"
    loop: 
    - {name: 'java', state: 'present'}
    - {name: 'ngnix', state: 'absent'}
    - {name: 'mysql', state: 'absent'}